displayName=Smart Key Remapping
author=Taz441
description=Key remapping with more seamless typing features
tags=chat,key-remapping,wasd
version=
plugins=com.smartkeyremapping.SmartKeyRemappingPlugin
build=standard
