displayName=Smart Key Remapping
author=Taz441
description=Key remapping with more seamless typing features
tags=chat,wasd,camera,fkeys,enter,typing,hotkey,key,remapping,messages
version=
plugins=com.smartkeyremapping.SmartKeyRemappingPlugin
build=standard
