displayName=Smart Key Remapping
author=Taz441
description=Key remapping with controllable chat focus
tags=chat,key-remapping,wasd
version=
plugins=com.smartKeyremapping.SmartKeyRemappingPlugin
build=standard